### ISSUE TITLE
style

### ISSUE THREAD

**Issue by berruno** [RamChilla/jquery-simple-maps#1]
is it possible to use styles?

**Comment by RamChilla** [comment]
Hey @berruno , sorry for the late response (half a year later, my bad). I'm assuming you're asking about map styles. Although its not documented, you can add your styles array to the `options.mapSetup` object.

Something like the following should work:
```
// your map styles array or json
var mapStylesArray = yourMapStyles;

//initialize jquery plugin with map styles on mapSetup option
$('myMapElement').simpleMap({
    mapSetup: {
         styles: mapStylesArray
     }
})
```
Keep in mind the plugin doesn't currently consider map styles, but I do plan on including better styling support and documentation on the next iteration. Let me know how it works out.

**Comment by RamChilla** [comment]
I added an example of how to use on here [https://ramchilla.github.io/jquery-simple-maps/](https://ramchilla.github.io/jquery-simple-maps/)
